#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SilentNotes.Android.Resource", IsApplication=true)]

namespace SilentNotes.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int font = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fontProviderAuthority = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderPackage = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderQuery = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderSystemFontFamily = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontStyle = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontVariationSettings = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontWeight = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int lStar = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int nestedScrollViewStyle = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int postSplashScreenTheme = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int queryPatterns = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int shortcutMatchRequired = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int splashScreenIconSize = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int ttcIndex = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int windowSplashScreenAnimatedIcon = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int windowSplashScreenAnimationDuration = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int windowSplashScreenBackground = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int windowSplashScreenIconBackgroundColor = 2130771990;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public const int enable_system_alarm_service_default = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int enable_system_foreground_service_default = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int enable_system_job_service_default = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int workmanager_test_configuration = 2130837507;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int androidx_core_ripple_material_light = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int androidx_core_secondary_text_default_material_light = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int browser_actions_bg_grey = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int browser_actions_divider_color = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int browser_actions_text_color = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int browser_actions_title_color = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int notification_action_color_filter = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int notification_icon_bg_color = 2130903047;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int browser_actions_context_menu_max_width = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int browser_actions_context_menu_min_padding = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_inset_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_inset_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_button_padding_horizontal_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int compat_button_padding_vertical_material = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int compat_control_corner_material = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int compat_notification_large_icon_max_height = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int compat_notification_large_icon_max_width = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_action_icon_size = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_action_text_size = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_big_circle_margin = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_content_margin_start = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_large_icon_height = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_large_icon_width = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_main_column_padding_top = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_media_narrow_margin = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_right_icon_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_right_side_padding_top = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_small_icon_background_padding = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_small_icon_size_as_large = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int notification_subtext_size = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int notification_top_pad = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int notification_top_pad_large_text = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int splashscreen_icon_mask_size_no_background = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int splashscreen_icon_mask_size_with_background = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int splashscreen_icon_mask_stroke_no_background = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int splashscreen_icon_mask_stroke_with_background = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int splashscreen_icon_size = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int splashscreen_icon_size_no_background = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int splashscreen_icon_size_with_background = 2130968606;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int compat_splash_screen = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int compat_splash_screen_no_icon_background = 2131034113;
			
			// aapt resource value: 0x7F050005
			public const int icon_background = 2131034117;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_launcher_background = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int ic_launcher_foreground = 2131034116;
			
			// aapt resource value: 0x7F050006
			public const int notification_action_background = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_bg = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_bg_low = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_bg_low_normal = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_bg_low_pressed = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_bg_normal = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_bg_normal_pressed = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_icon_background = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notification_template_icon_bg = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int notification_template_icon_low_bg = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int notification_tile_bg = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notify_panel_notification_icon_bg = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int silent_notes_256 = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int splash_screen = 2131034131;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int accessibility_action_clickable_span = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int accessibility_custom_action_0 = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int accessibility_custom_action_1 = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int accessibility_custom_action_10 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int accessibility_custom_action_11 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int accessibility_custom_action_12 = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int accessibility_custom_action_13 = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int accessibility_custom_action_14 = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int accessibility_custom_action_15 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int accessibility_custom_action_16 = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int accessibility_custom_action_17 = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int accessibility_custom_action_18 = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int accessibility_custom_action_19 = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int accessibility_custom_action_2 = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int accessibility_custom_action_20 = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int accessibility_custom_action_21 = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int accessibility_custom_action_22 = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int accessibility_custom_action_23 = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int accessibility_custom_action_24 = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int accessibility_custom_action_25 = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int accessibility_custom_action_26 = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int accessibility_custom_action_27 = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int accessibility_custom_action_28 = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int accessibility_custom_action_29 = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int accessibility_custom_action_3 = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int accessibility_custom_action_30 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int accessibility_custom_action_31 = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int accessibility_custom_action_4 = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int accessibility_custom_action_5 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int accessibility_custom_action_6 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int accessibility_custom_action_7 = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int accessibility_custom_action_8 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int accessibility_custom_action_9 = 2131099680;
			
			// aapt resource value: 0x7F060025
			public const int actions = 2131099685;
			
			// aapt resource value: 0x7F060021
			public const int action_container = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int action_divider = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int action_image = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int action_text = 2131099684;
			
			// aapt resource value: 0x7F060026
			public const int async = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int blocking = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int browser_actions_header_text = 2131099688;
			
			// aapt resource value: 0x7F06002B
			public const int browser_actions_menu_items = 2131099691;
			
			// aapt resource value: 0x7F060029
			public const int browser_actions_menu_item_icon = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int browser_actions_menu_item_text = 2131099690;
			
			// aapt resource value: 0x7F06002C
			public const int browser_actions_menu_view = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int busyIndicator = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int chronometer = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int dialog_button = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int forever = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int icon = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int icon_group = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int info = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int italic = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int line1 = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int line3 = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int normal = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int notification_background = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int notification_main_column = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int notification_main_column_container = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int right_icon = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int right_side = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int splashscreen_icon_view = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int tag_accessibility_actions = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int tag_accessibility_clickable_spans = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int tag_accessibility_heading = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int tag_accessibility_pane_title = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int tag_on_apply_window_listener = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int tag_on_receive_content_listener = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int tag_on_receive_content_mime_types = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int tag_screen_reader_focusable = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int tag_state_description = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int tag_transition_group = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int tag_unhandled_key_event_manager = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int tag_unhandled_key_listeners = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int tag_window_insets_animation_callback = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int text = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int text2 = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int time = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int title = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int view_tree_lifecycle_owner = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int webView = 2131099728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int default_icon_animation_duration = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int browser_actions_context_menu_page = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int browser_actions_context_menu_row = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int custom_dialog = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int Main = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int notification_action = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_action_tombstone = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_template_custom_big = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int notification_template_icon_group = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int notification_template_part_chronometer = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int notification_template_part_time = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int splash_screen_view = 2131230730;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int androidx_startup = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int copy_toast_msg = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int fallback_menu_item_copy_link = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int fallback_menu_item_open_in_browser = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int fallback_menu_item_share_link = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int status_bar_notification_info_overflow = 2131296261;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int Base_Theme_SplashScreen = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int Base_Theme_SplashScreen_DayNight = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int Base_Theme_SplashScreen_Light = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int Base_v21_Theme_SplashScreen = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int Base_v21_Theme_SplashScreen_Light = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Base_v27_Theme_SplashScreen = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Base_v27_Theme_SplashScreen_Light = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int MainTheme = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int MainTheme_Base = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int TextAppearance_Compat_Notification = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int TextAppearance_Compat_Notification_Info = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int TextAppearance_Compat_Notification_Line2 = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int TextAppearance_Compat_Notification_Time = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int TextAppearance_Compat_Notification_Title = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int Theme_App_Starting = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int Theme_SplashScreen = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int Theme_SplashScreen_Common = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int Theme_SplashScreen_IconBackground = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int Widget_Compat_NotificationActionContainer = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int Widget_Compat_NotificationActionText = 2131361811;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F01000F,0x7F010010 }
			public static int[] Capability = new int[] {
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int Capability_queryPatterns = 0;
			
			// aapt resource value: 1
			public const int Capability_shortcutMatchRequired = 1;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x1010647,0x7F010000,0x7F01000C }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					16844359,
					2130771968,
					2130771980};
			
			// aapt resource value: 3
			public const int ColorStateListItem_alpha = 3;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: 2
			public const int ColorStateListItem_android_lStar = 2;
			
			// aapt resource value: 4
			public const int ColorStateListItem_lStar = 4;
			
			// aapt resource value: { 0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008 }
			public static int[] FontFamily = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010001,0x7F010009,0x7F01000A,0x7F01000B,0x7F010012 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771969,
					2130771977,
					2130771978,
					2130771979,
					2130771986};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: 6
			public const int FontFamily_fontProviderSystemFontFamily = 6;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int image_share_filepaths = 2131492864;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
