#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentNotes.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "NoteRepositoryRazorView.cshtml"
using SilentNotes.ViewModels;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "17.1.0.324")]
public partial class NoteRepositoryRazorView : NoteRepositoryRazorViewBase
{

#line hidden

#line 2 "NoteRepositoryRazorView.cshtml"
public NoteRepositoryViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <base");

WriteAttribute ("href", " href=\"", "\""

#line 7 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlBase

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <title>SilentNotes</title>\r\n    <meta");

WriteLiteral(" charset=\"UTF-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no" +
"\"");

WriteLiteral(">\r\n\r\n    <link");

WriteAttribute ("href", " href=\"", "\""

#line 12 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["bootstrap-css"]

#line default
#line hidden
, false)
);
WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute ("href", " href=\"", "\""

#line 13 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["silentnotes-css"]

#line default
#line hidden
, false)
);
WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute ("href", " href=\"", "\""

#line 14 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.Theme.DarkMode ? @Model.HtmlRecource["silentnotes-dark-css"] : @Model.HtmlRecource["silentnotes-light-css"]

#line default
#line hidden
, false)
);
WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute ("href", " href=\"", "\""

#line 15 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["silentnotes-notecard-css"]

#line default
#line hidden
, false)
);
WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteAttribute ("src", " src=\"", "\""

#line 17 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["vue-js"]

#line default
#line hidden
, false)
);
WriteLiteral("></script>\r\n    <script");

WriteAttribute ("src", " src=\"", "\""

#line 18 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["bootstrap-js"]

#line default
#line hidden
, false)
);
WriteLiteral("></script>\r\n    <script");

WriteAttribute ("src", " src=\"", "\""

#line 19 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["jqueryjs"]

#line default
#line hidden
, false)
);
WriteLiteral("></script>\r\n    <script");

WriteAttribute ("src", " src=\"", "\""

#line 20 "NoteRepositoryRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["silentnotes-js"]

#line default
#line hidden
, false)
);
WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"Sortable.min.js\"");

WriteLiteral("></script>\r\n\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\nbody {\r\n");

WriteLiteral("    ");


#line 25 "NoteRepositoryRazorView.cshtml"
Write(Model.Theme.CssBackgroundColor);


#line default
#line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");


#line 26 "NoteRepositoryRazorView.cshtml"
Write(Model.Theme.CssBackgroundImage);


#line default
#line hidden
WriteLiteral("\r\n}\r\n\r\n.note-viewer {\r\n    font-size: ");


#line 30 "NoteRepositoryRazorView.cshtml"
           Write(Model.NoteBaseFontSize);


#line default
#line hidden
WriteLiteral("px !important;\r\n}\r\n.note-card {\r\n    min-height: ");


#line 33 "NoteRepositoryRazorView.cshtml"
            Write(Model.NoteMinHeight);


#line default
#line hidden
WriteLiteral("px;\r\n    max-height: ");


#line 34 "NoteRepositoryRazorView.cshtml"
            Write(Model.NoteMaxHeight);


#line default
#line hidden
WriteLiteral("px;\r\n}\r\n\r\ndiv .note-viewer.over-view.checklist p::before { content: ");


#line 37 "NoteRepositoryRazorView.cshtml"
                                                            WriteLiteral(Model.Icon.LoadIconAsCssUrl("checkbox-blank-outline", new[] { new KeyValuePair<string, string>("fill", "#000000") }));

#line default
#line hidden
WriteLiteral("; }\r\ndiv.dark .note-viewer.over-view.checklist p::before { content: ");


#line 38 "NoteRepositoryRazorView.cshtml"
                                                                 WriteLiteral(Model.Icon.LoadIconAsCssUrl("checkbox-blank-outline", new[] { new KeyValuePair<string, string>("fill", "#FFFFFF") }));

#line default
#line hidden
WriteLiteral("; }\r\ndiv .note-viewer.over-view.checklist p.done::before { content: ");


#line 39 "NoteRepositoryRazorView.cshtml"
                                                                 WriteLiteral(Model.Icon.LoadIconAsCssUrl("check-box-outline", new[] { new KeyValuePair<string, string>("fill", "#000000") }));

#line default
#line hidden
WriteLiteral("; }\r\ndiv.dark .note-viewer.over-view.checklist p.done::before { content: ");


#line 40 "NoteRepositoryRazorView.cshtml"
                                                                      WriteLiteral(Model.Icon.LoadIconAsCssUrl("check-box-outline", new[] { new KeyValuePair<string, string>("fill", "#FFFFFF") }));

#line default
#line hidden
WriteLiteral("; }\r\ndiv .note-viewer.over-view.checklist p.disabled::before { content: ");


#line 41 "NoteRepositoryRazorView.cshtml"
                                                                     WriteLiteral(Model.Icon.LoadIconAsCssUrl("checkbox-blank-outline", new[] { new KeyValuePair<string, string>("fill", "#000000") }));

#line default
#line hidden
WriteLiteral("; }\r\ndiv.dark .note-viewer.over-view.checklist p.disabled::before { content: ");


#line 42 "NoteRepositoryRazorView.cshtml"
                                                                          WriteLiteral(Model.Icon.LoadIconAsCssUrl("checkbox-blank-outline", new[] { new KeyValuePair<string, string>("fill", "#FFFFFF") }));

#line default
#line hidden
WriteLiteral("; }\r\n\r\n.locked {\r\n    position: absolute;\r\n    width: 48px;\r\n    height: 48px;\r\n " +
"   top: 0;\r\n    bottom: 0;\r\n    left: 0;\r\n    right: 0;\r\n    margin: auto;\r\n}\r\n." +
"locked svg {\r\n    width: 100%;\r\n    height: 100%;\r\n    fill: rgba(160, 160, 160," +
" 0.4);\r\n}\r\n.locked.dark svg {\r\n    fill: rgba(204, 204, 204, 0.4);\r\n}\r\n.greenish" +
", .greenish.dark {\r\n\tfill: #0a480a;\r\n\tbackground-color: #1bbb1b;\r\n}\r\n.reddish, ." +
"reddish.dark {\r\n\tfill: #470a0a;\r\n\tbackground-color: #be1c1c;\r\n}\r\n.fab { right: 3" +
".2em; } /* should not cover icons */\r\n    </style>\r\n    <script>\r\n        functi" +
"on showNote(e) {\r\n            vueCommandExecute(\'ShowNoteCommand\', e.currentTarg" +
"et.parentNode.attributes[\'data-note\'].value);\r\n        }\r\n\r\n        function del" +
"eteNote(e) {\r\n            vueCommandExecute(\'DeleteNoteCommand\', e.currentTarget" +
".parentNode.attributes[\'data-note\'].value);\r\n        }\r\n\r\n        function addTo" +
"Safe(e) {\r\n            vueCommandExecute(\'AddToSafeCommand\', e.currentTarget.par" +
"entNode.attributes[\'data-note\'].value);\r\n        }\r\n\r\n        function removeFro" +
"mSafe(e) {\r\n            vueCommandExecute(\'RemoveFromSafeCommand\', e.currentTarg" +
"et.parentNode.attributes[\'data-note\'].value);\r\n        }\r\n\r\n        function scr" +
"ollToTop() {\r\n            var element = document.querySelector(\'#content\');\r\n   " +
"         element.scrollTop = 0;\r\n        }\r\n\r\n        function scrollToBottom() " +
"{\r\n            var element = document.querySelector(\'#content\');\r\n            el" +
"ement.scrollTop = element.scrollHeight;\r\n        }\r\n\r\n        function setSelect" +
"edTag(e) {\r\n            vm.SelectedTag = e.currentTarget.attributes[\'data-tag\']." +
"value;\r\n        }\r\n\r\n");


#line 103 "NoteRepositoryRazorView.cshtml"
        

#line default
#line hidden

#line 103 "NoteRepositoryRazorView.cshtml"
          WriteLiteral(Model.VueDataBindingScript);

#line default
#line hidden
WriteLiteral("\r\n    </script>\r\n</head>\r\n<body><div");

WriteLiteral(" id=\"vueDataBinding\"");

WriteLiteral(">\r\n<aside>\r\n    <nav>\r\n        <div");

WriteLiteral(" id=\"nav-group-left\"");

WriteLiteral(" class=\"nav-group\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" id=\"nav-group-right\"");

WriteLiteral(" class=\"nav-group\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"tag-selector\"");

WriteLiteral(" class=\"nav-item nav-item-button dropdown-toggle\"");

WriteLiteral(" data-bs-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"tag-selector-text\"");

WriteAttribute ("v-if", " v-if=\"", "\""
, Tuple.Create<string,object,bool> ("", "SelectedTag==\'", true)

#line 114 "NoteRepositoryRazorView.cshtml"
                                 , Tuple.Create<string,object,bool> ("", Model.AllNotesTagFilter

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral("><svg");

WriteLiteral(" width=\'22\'");

WriteLiteral(" height=\'22\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\'#svg-tag-multiple\'");

WriteLiteral("/></svg></span>\r\n                    <span");

WriteLiteral(" class=\"tag-selector-text\"");

WriteAttribute ("v-else-if", " v-else-if=\"", "\""
, Tuple.Create<string,object,bool> ("", "SelectedTag==\'", true)

#line 115 "NoteRepositoryRazorView.cshtml"
                                      , Tuple.Create<string,object,bool> ("", Model.WithoutTagFilter

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral("><svg");

WriteLiteral(" width=\'20\'");

WriteLiteral(" height=\'20\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\'#svg-tag-off\'");

WriteLiteral("/></svg></span>\r\n                    <span");

WriteLiteral(" class=\"tag-selector-text\"");

WriteLiteral(" v-else");

WriteLiteral(" v-bind:title=\"SelectedTag\"");

WriteLiteral(">{{SelectedTag}}</span>\r\n                </button>\r\n                <div");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                    <template");

WriteLiteral(" v-for=\"Tag in Tags\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteAttribute ("v-if", " v-if=\"", "\""
, Tuple.Create<string,object,bool> ("", "Tag==\'", true)

#line 120 "NoteRepositoryRazorView.cshtml"
                        , Tuple.Create<string,object,bool> ("", Model.AllNotesTagFilter

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral(" onclick=\"setSelectedTag(event);\"");

WriteLiteral(" v-bind:data-tag=\"Tag\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'22\'");

WriteLiteral(" height=\'22\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\'#svg-tag-multiple\'");

WriteLiteral("/></svg> {{Tag}}</div>\r\n                        <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteAttribute ("v-else-if", " v-else-if=\"", "\""
, Tuple.Create<string,object,bool> ("", "Tag==\'", true)

#line 121 "NoteRepositoryRazorView.cshtml"
                             , Tuple.Create<string,object,bool> ("", Model.WithoutTagFilter

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral(" onclick=\"setSelectedTag(event);\"");

WriteLiteral(" v-bind:data-tag=\"Tag\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'20\'");

WriteLiteral(" height=\'20\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\'#svg-tag-off\'");

WriteLiteral("/></svg> {{Tag}}</div>\r\n                        <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-else");

WriteLiteral(" onclick=\"setSelectedTag(event);\"");

WriteLiteral(" v-bind:data-tag=\"Tag\"");

WriteLiteral(">{{Tag}}</div>\r\n                    </template>\r\n                </div>\r\n        " +
"    </span>\r\n\r\n            <div");

WriteLiteral(" class=\"nav-item nav-item-filter\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"Filter\"");

WriteLiteral(" class=\"\"");

WriteLiteral(" v-on:input=\"Filter = $event.target.value;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" v-focus");

WriteAttribute ("value", " value=\"", "\""

#line 128 "NoteRepositoryRazorView.cshtml"
                                                                                  , Tuple.Create<string,object,bool> ("", Model.Filter

#line default
#line hidden
, false)
);
WriteLiteral("/>\r\n                <div");

WriteLiteral(" id=\"filter-icon-placeholder\"");

WriteLiteral(">\r\n                    <svg");

WriteLiteral(" id=\"filter-icon\"");

WriteLiteral(" v-show=\"!IsFiltered\"");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-magnify\"");

WriteLiteral("/></svg>\r\n                    <svg");

WriteLiteral(" id=\"filter-cancel-icon\"");

WriteLiteral(" v-cloak");

WriteLiteral(" v-show=\"IsFiltered\"");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral(" v-on:click=\"ClearFilterCommand\"");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-close-circle-outline\"");

WriteLiteral("/></svg>\r\n                </div>\r\n            </div>\r\n    \r\n            <div");

WriteLiteral(" class=\"nav-item nav-item-separator\"");

WriteLiteral("></div>\r\n\r\n            <button");

WriteLiteral(" class=\"nav-item nav-item-button\"");

WriteLiteral(" v-on:click=\"SynchronizeCommand\"");

WriteAttribute ("title", " title=\"", "\""

#line 137 "NoteRepositoryRazorView.cshtml"
                                                     , Tuple.Create<string,object,bool> ("", Model.Language["sync_notes"]

#line default
#line hidden
, false)
);
WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\'#svg-cloud-sync\'");

WriteLiteral("/></svg></button>\r\n\r\n            <span");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"navOverflowMenu\"");

WriteLiteral(" class=\"nav-item nav-item-button\"");

WriteLiteral(" data-bs-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                    <svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\'#svg-dots-vertical\'");

WriteLiteral(" /></svg>\r\n                </button>\r\n                <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-end\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"NewNoteCommand\"");

WriteLiteral("><svg><use");

WriteLiteral(" xlink:href=\"#svg-note-text-outline\"");

WriteLiteral("/></svg> ");


#line 144 "NoteRepositoryRazorView.cshtml"
                                                                                                                            Write(Model.Language["note_create_new"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"NewChecklistCommand\"");

WriteLiteral("><svg><use");

WriteLiteral(" xlink:href=\"#svg-order-bool-ascending-variant\"");

WriteLiteral("/></svg> ");


#line 145 "NoteRepositoryRazorView.cshtml"
                                                                                                                                            Write(Model.Language["checklist_create_new"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"ShowRecycleBinCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-delete-empty\"");

WriteLiteral("/></svg> ");


#line 146 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                         Write(Model.Language["show_recyclebin"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"ShowExportCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-export\"");

WriteLiteral("/></svg> ");


#line 147 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                               Write(Model.Language["show_export"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-divider\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("  v-on:click=\"OpenSafeCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-safe-square-outline\"");

WriteLiteral("/></svg> ");


#line 149 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                           Write(Model.Language["safe_open"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" hidden");

WriteLiteral(" v-on:click=\"CloseSafeCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-safe-square-outline\"");

WriteLiteral("/></svg> ");


#line 150 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                                  Write(Model.Language["safe_close"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"ChangeSafePasswordCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-lock-reset\"");

WriteLiteral("/></svg> ");


#line 151 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                           Write(Model.Language["safe_change_password"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-divider\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"ShowTransferCodeCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-key\"");

WriteLiteral("/></svg> ");


#line 153 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                  Write(Model.Language["show_transfer_code"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"ShowSettingsCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-settings\"");

WriteLiteral("/></svg> ");


#line 154 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                   Write(Model.Language["show_settings"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"ShowInfoCommand\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-information\"");

WriteLiteral("/></svg> ");


#line 155 "NoteRepositoryRazorView.cshtml"
                                                                                                                                                                  Write(Model.Language["show_info"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </span>\r\n        </div>\r\n    </nav>\r\n" +
"</aside>\r\n\r\n<main");

WriteLiteral(" id=\"content\"");

WriteLiteral(" v-pre");

WriteLiteral(" class=\"p-2\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" id=\"note-repository\"");

WriteLiteral("></ul>\r\n</main>\r\n\r\n<div");

WriteLiteral(" class=\"fab dropup\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" data-bs-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><svg");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-plus\"");

WriteLiteral("/></svg></a>\r\n    <div");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" v-on:click=\"NewNoteCommand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><svg><use");

WriteLiteral(" xlink:href=\"#svg-note-text-outline\"");

WriteLiteral(" /></svg></a>\r\n        <a");

WriteLiteral(" v-on:click=\"NewChecklistCommand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><svg><use");

WriteLiteral(" xlink:href=\"#svg-order-bool-ascending-variant\"");

WriteLiteral(" /></svg></a>\r\n    </div>\r\n</div>\r\n\r\n<div hidden>\r\n");


#line 175 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 175 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("magnify", new[] { new KeyValuePair<string, string>("id", "svg-magnify") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 176 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 176 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("close-circle-outline", new[] { new KeyValuePair<string, string>("id", "svg-close-circle-outline") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 177 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 177 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("arrow-all", new[] { new KeyValuePair<string, string>("id", "svg-arrow-all") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 178 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 178 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("lock", new[] { new KeyValuePair<string, string>("id", "svg-lock") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 179 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 179 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("lock-open-variant", new[] { new KeyValuePair<string, string>("id", "svg-lock-open-variant") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 180 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 180 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("lock-outline", new[] { new KeyValuePair<string, string>("id", "svg-lock-outline") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 181 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 181 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("delete", new[] { new KeyValuePair<string, string>("id", "svg-delete") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 182 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 182 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("note-text-outline", new[] { new KeyValuePair<string, string>("id", "svg-note-text-outline") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 183 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 183 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("pin", new[] { new KeyValuePair<string, string>("id", "svg-pin") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 184 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 184 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("order-bool-ascending-variant", new[] { new KeyValuePair<string, string>("id", "svg-order-bool-ascending-variant") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 185 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 185 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("tag-multiple", new[] { new KeyValuePair<string, string>("id", "svg-tag-multiple") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 186 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 186 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("tag-off", new[] { new KeyValuePair<string, string>("id", "svg-tag-off") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 187 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 187 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("cloud-sync", new[] { new KeyValuePair<string, string>("id", "svg-cloud-sync") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 188 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 188 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("dots-vertical", new[] { new KeyValuePair<string, string>("id", "svg-dots-vertical") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 189 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 189 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("delete-empty", new[] { new KeyValuePair<string, string>("id", "svg-delete-empty") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 190 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 190 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("export", new[] { new KeyValuePair<string, string>("id", "svg-export") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 191 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 191 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("safe-square-outline", new[] { new KeyValuePair<string, string>("id", "svg-safe-square-outline") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 192 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 192 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("lock-reset", new[] { new KeyValuePair<string, string>("id", "svg-lock-reset") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 193 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 193 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("key", new[] { new KeyValuePair<string, string>("id", "svg-key") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 194 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 194 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("settings", new[] { new KeyValuePair<string, string>("id", "svg-settings") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 195 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 195 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("information", new[] { new KeyValuePair<string, string>("id", "svg-information") }));

#line default
#line hidden
WriteLiteral("\r\n");


#line 196 "NoteRepositoryRazorView.cshtml"
    

#line default
#line hidden

#line 196 "NoteRepositoryRazorView.cshtml"
      WriteLiteral(Model.Icon.LoadIcon("plus", new[] { new KeyValuePair<string, string>("id", "svg-plus") }));

#line default
#line hidden
WriteLiteral("\r\n</div>\r\n</div></body>\r\n</html>\r\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class NoteRepositoryRazorViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
