#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentNotes.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "OpenSafeRazorView.cshtml"
using SilentNotes.ViewModels;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "16.5.0.521")]
public partial class OpenSafeRazorView : OpenSafeRazorViewBase
{

#line hidden

#line 2 "OpenSafeRazorView.cshtml"
public OpenSafeViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <base");

WriteAttribute ("href", " href=\"", "\""

#line 7 "OpenSafeRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlBase

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <title>SilentNotes</title>\r\n    <meta");

WriteLiteral(" charset=\"UTF-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no" +
"\"");

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" href=\"bootstrap.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"silentnotes.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute ("href", " href=\"", "\""

#line 14 "OpenSafeRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.Theme.DarkMode ? "silentnotes.dark.css" : "silentnotes.light.css"

#line default
#line hidden
, false)
);
WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" src=\"jquery-3.4.1.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"bootstrap.bundle.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"silentnotes.js\"");

WriteLiteral("></script>\r\n\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        .background-icon {\r\n            right: -110px;\r\n            top: -172p" +
"x;\r\n        }\r\n    </style>\r\n    <script>\r\n        $(function () {\r\n            " +
"addShortcuts();\r\n        });\r\n    </script>\r\n</head>\r\n<body>\r\n    <nav");

WriteLiteral(" id=\"navigation\"");

WriteLiteral(" class=\"d-flex\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"nav-item mr-auto shortcut-escape\"");

WriteLiteral(" onclick=\"bind(event);\"");

WriteLiteral(" data-binding=\"GoBack\"");

WriteAttribute ("title", " title=\"", "\""

#line 34 "OpenSafeRazorView.cshtml"
                                                                      , Tuple.Create<string,object,bool> ("", Model.Language["back"]

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 34 "OpenSafeRazorView.cshtml"
                                                                                                                                        WriteLiteral(Model.Icon["arrow-left"]);

#line default
#line hidden
WriteLiteral("</button>\r\n\r\n        <div");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(" id=\"navOverflowMenu\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n");


#line 38 "OpenSafeRazorView.cshtml"
                

#line default
#line hidden

#line 38 "OpenSafeRazorView.cshtml"
                  WriteLiteral(Model.Icon["dots-vertical"]);

#line default
#line hidden
WriteLiteral("\r\n            </button>\r\n            <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(" aria-labelledby=\"navOverflowMenu\"");

WriteLiteral(">\r\n                <div");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "dropdown-item", true)
, Tuple.Create<string,object,bool> (" ", new Action<System.IO.TextWriter> (__razor_attribute_value_writer => {

#line 41 "OpenSafeRazorView.cshtml"
                                           if (!Model.SafeExists) { 

#line default
#line hidden

#line 41 "OpenSafeRazorView.cshtml"
                              WriteTo(__razor_attribute_value_writer, "disabled");


#line default
#line hidden

#line 41 "OpenSafeRazorView.cshtml"
                                                                                  ; }

#line default
#line hidden
}), false)
);
WriteLiteral(" onclick=\"bind(event);\"");

WriteLiteral(" data-binding=\"ResetSafeCommand\"");

WriteLiteral("><svg><use");

WriteLiteral(" xlink:href=\"#svg-safe-square-outline\"");

WriteLiteral(" /></svg> ");


#line 41 "OpenSafeRazorView.cshtml"
                                                                                                                                                                                                  Write(Model.Language["safe_reset"]);


#line default
#line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n    </nav>\r\n\r\n    <div");

WriteLiteral(" id=\"content\"");

WriteLiteral(" class=\"container-fluid p-4\"");

WriteLiteral(">\r\n        <svg");

WriteLiteral(" class=\"background-icon\"");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-safe-square-outline\"");

WriteLiteral(" /></svg>\r\n\r\n");


#line 49 "OpenSafeRazorView.cshtml"
        

#line default
#line hidden

#line 49 "OpenSafeRazorView.cshtml"
         if (Model.SafeExists)
        {


#line default
#line hidden
WriteLiteral("            <h2>");


#line 51 "OpenSafeRazorView.cshtml"
           Write(Model.Language["safe_open"]);


#line default
#line hidden
WriteLiteral("</h2>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"my-4\"");

WriteLiteral(">");


#line 52 "OpenSafeRazorView.cshtml"
                         Write(Model.Language["safe_open_existing"]);


#line default
#line hidden
WriteLiteral("</div>\r\n");


#line 53 "OpenSafeRazorView.cshtml"
        }
        else
        {


#line default
#line hidden
WriteLiteral("            <h2>");


#line 56 "OpenSafeRazorView.cshtml"
           Write(Model.Language["safe_new"]);


#line default
#line hidden
WriteLiteral("</h2>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"my-4\"");

WriteLiteral(">");


#line 57 "OpenSafeRazorView.cshtml"
                         Write(Model.Language["safe_open_new"]);


#line default
#line hidden
WriteLiteral("</div>\r\n");


#line 58 "OpenSafeRazorView.cshtml"
        }


#line default
#line hidden
WriteLiteral("\r\n        <form");

WriteLiteral(" class=\"mb-4 col-md-9\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label col-md-3\"");

WriteLiteral(" for=\"Password\"");

WriteLiteral(">");


#line 62 "OpenSafeRazorView.cshtml"
                                                                 Write(Model.Language["cloud_password"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" oninput=\"bind(event)\"");

WriteLiteral(" data-binding=\"Password\"");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" autofocus>\r\n                    <div");

WriteLiteral(" class=\"invalid-feedback\"");

WriteLiteral(">");


#line 65 "OpenSafeRazorView.cshtml"
                                             Write(Model.Language["password_short_error"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-row form-group mb-4\"");

WriteLiteral(" ");


#line 68 "OpenSafeRazorView.cshtml"
                                                   if (Model.SafeExists) { 

#line default
#line hidden

#line 68 "OpenSafeRazorView.cshtml"
                                                                       Write("hidden");


#line default
#line hidden

#line 68 "OpenSafeRazorView.cshtml"
                                                                                       ; }

#line default
#line hidden
WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label col-md-3\"");

WriteLiteral(" for=\"PasswordConfirmation\"");

WriteLiteral(">");


#line 69 "OpenSafeRazorView.cshtml"
                                                                             Write(Model.Language["safe_confirm_password"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" oninput=\"bind(event)\"");

WriteLiteral(" data-binding=\"PasswordConfirmation\"");

WriteLiteral(" id=\"PasswordConfirmation\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"invalid-feedback\"");

WriteLiteral(">");


#line 72 "OpenSafeRazorView.cshtml"
                                             Write(Model.Language["password_confirmation_error"]);


#line default
#line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary mb-2 shortcut-enter\"");

WriteLiteral(" onclick=\"bind(event)\"");

WriteLiteral(" data-binding=\"OkCommand\"");

WriteLiteral(">");


#line 76 "OpenSafeRazorView.cshtml"
                                                                                                                        Write(Model.Language["ok"]);


#line default
#line hidden
WriteLiteral("</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary mb-2\"");

WriteLiteral(" onclick=\"bind(event)\"");

WriteLiteral(" data-binding=\"CancelCommand\"");

WriteLiteral(">");


#line 77 "OpenSafeRazorView.cshtml"
                                                                                                               Write(Model.Language["cancel"]);


#line default
#line hidden
WriteLiteral("</button>\r\n        </form>\r\n\r\n");


#line 80 "OpenSafeRazorView.cshtml"
        

#line default
#line hidden

#line 80 "OpenSafeRazorView.cshtml"
         if (!Model.SafeExists)
        {


#line default
#line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success my-4\"");

WriteLiteral(">");


#line 82 "OpenSafeRazorView.cshtml"
                                             Write(Model.Language["safe_password_requirement"]);


#line default
#line hidden
WriteLiteral("</div>\r\n");


#line 83 "OpenSafeRazorView.cshtml"
        }


#line default
#line hidden
WriteLiteral("    </div>\r\n\r\n    <div hidden>\r\n");


#line 87 "OpenSafeRazorView.cshtml"
        

#line default
#line hidden

#line 87 "OpenSafeRazorView.cshtml"
          WriteLiteral(Model.Icon.LoadIcon("safe-square-outline", new[] { new KeyValuePair<string, string>("id", "svg-safe-square-outline") }));

#line default
#line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class OpenSafeRazorViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
