#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentNotes.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "SettingsRazorView.cshtml"
using SilentNotes.ViewModels;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "17.4.0.312")]
public partial class SettingsRazorView : SettingsRazorViewBase
{

#line hidden

#line 2 "SettingsRazorView.cshtml"
public SettingsViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <base");

WriteAttribute ("href", " href=\"", "\""

#line 7 "SettingsRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlBase

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <title>SilentNotes</title>\r\n    <meta");

WriteLiteral(" charset=\"UTF-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no" +
"\"");

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" href=\"bootstrap.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"silentnotes.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute ("href", " href=\"", "\""

#line 14 "SettingsRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.Theme.DarkMode ? "silentnotes.dark.css" : "silentnotes.light.css"

#line default
#line hidden
, false)
);
WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteAttribute ("src", " src=\"", "\""

#line 16 "SettingsRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["vuejs"]

#line default
#line hidden
, false)
);
WriteLiteral("></script>\r\n    <script");

WriteAttribute ("src", " src=\"", "\""

#line 17 "SettingsRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", Model.HtmlRecource["jqueryjs"]

#line default
#line hidden
, false)
);
WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"bootstrap.bundle.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"silentnotes.js\"");

WriteLiteral("></script>\r\n\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        .background-icon {
            right: -128px;
            top: -154px;
        }

        #theme-control {
            height: 90px;
        }

        #color-control {
            height: 50px;
        }

        .theme-list,
        .color-list {
            max-height: 360px;
            overflow-y: scroll;
        }

        .theme-item,
        .color-item {
            display: inline-block;
            width: 90px;
            height: 128px;
        }

        .color-btn { color: black; }
        .color-btn.dark { color: white; }
    </style>
    <script>
");


#line 52 "SettingsRazorView.cshtml"
        

#line default
#line hidden

#line 52 "SettingsRazorView.cshtml"
          WriteLiteral(Model.VueDataBindingScript);

#line default
#line hidden
WriteLiteral("\r\n    </script>\r\n</head>\r\n<body><div");

WriteLiteral(" id=\"vueDataBinding\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" id=\"navigation\"");

WriteLiteral(" class=\"d-flex\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"nav-item mr-auto\"");

WriteLiteral(" v-on:click=\"GoBackCommand\"");

WriteAttribute ("title", " title=\"", "\""

#line 57 "SettingsRazorView.cshtml"
                                    , Tuple.Create<string,object,bool> ("", Model.Language["back"]

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 57 "SettingsRazorView.cshtml"
                                                                                                      WriteLiteral(Model.Icon["arrow-left"]);

#line default
#line hidden
WriteLiteral("</button>\r\n\r\n        <div");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(" id=\"navOverflowMenu\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n");


#line 61 "SettingsRazorView.cshtml"
                

#line default
#line hidden

#line 61 "SettingsRazorView.cshtml"
                  WriteLiteral(Model.Icon["dots-vertical"]);

#line default
#line hidden
WriteLiteral("\r\n            </button>\r\n            <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(" aria-labelledby=\"navOverflowMenu\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" v-on:click=\"TestNewLocalizationCommand\"");

WriteLiteral(">");


#line 64 "SettingsRazorView.cshtml"
                                                                                     WriteLiteral(Model.Icon["earth"]);

#line default
#line hidden
WriteLiteral(" ");


#line 64 "SettingsRazorView.cshtml"
                                                                                                                    Write(Model.Language["gui_localization_test"]);


#line default
#line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n    </nav>\r\n\r\n    <div");

WriteLiteral(" id=\"content\"");

WriteLiteral(" class=\"container-fluid p-4\"");

WriteLiteral(">\r\n        <svg");

WriteLiteral(" class=\"background-icon\"");

WriteLiteral(" width=\'24\'");

WriteLiteral(" height=\'24\'");

WriteLiteral(" viewBox=\'0 0 24 24\'");

WriteLiteral("><use");

WriteLiteral(" xlink:href=\"#svg-settings\"");

WriteLiteral(" /></svg>\r\n\r\n        <h2>");


#line 72 "SettingsRazorView.cshtml"
       Write(Model.Language["gui_texture"]);


#line default
#line hidden
WriteLiteral("</h2>\r\n        <form");

WriteLiteral(" class=\"mb-4 col-md-9 col-lg-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"theme-control\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"Theme\"");

WriteLiteral(" class=\"dropdown d-flex\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"theme-preview btn h-100 flex-fill\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" v-bind:style=\"{ backgroundImage: \'url(\' + SelectedThemeImage + \')\' }\"");

WriteLiteral(">\r\n                        </button>\r\n                        <div");

WriteLiteral(" class=\"dropdown-menu theme-list\"");

WriteLiteral(" aria-labelledby=\"themeChooser\"");

WriteLiteral(">\r\n");


#line 80 "SettingsRazorView.cshtml"
                            

#line default
#line hidden

#line 80 "SettingsRazorView.cshtml"
                             foreach (var theme in @Model.Theme.Themes)
                            {


#line default
#line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"dropdown-item theme-item\"");

WriteAttribute ("v-on:click", " v-on:click=\"", "\""
, Tuple.Create<string,object,bool> ("", "SelectedTheme=\'", true)

#line 82 "SettingsRazorView.cshtml"
                                                           , Tuple.Create<string,object,bool> ("", theme.Id

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background:", true)
, Tuple.Create<string,object,bool> (" ", "url(", true)

#line 82 "SettingsRazorView.cshtml"
                                                                                                , Tuple.Create<string,object,bool> ("", theme.Image

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("></div>\r\n");


#line 83 "SettingsRazorView.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n                </div" +
">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group col-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-check\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"form-check-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"UseSolidColorTheme\"");

WriteLiteral(" v-model=\"UseSolidColorTheme\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"form-check-label\"");

WriteLiteral(" for=\"UseSolidColorTheme\"");

WriteLiteral(">");


#line 92 "SettingsRazorView.cshtml"
                                                                            Write(Model.Language["gui_theme_solid_color"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                    </div>\r\n                </div>\r\n                <di" +
"v");

WriteLiteral(" class=\"form-group col-2\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"color\"");

WriteLiteral(" v-model=\"ColorForSolidThemeHex\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" v-model=\"SelectedThemeMode\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"Auto\"");

WriteLiteral(">");


#line 101 "SettingsRazorView.cshtml"
                                    Write(Model.Language["gui_theme_auto"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                    <option");

WriteLiteral(" value=\"Dark\"");

WriteLiteral(">");


#line 102 "SettingsRazorView.cshtml"
                                    Write(Model.Language["gui_theme_dark"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                    <option");

WriteLiteral(" value=\"Light\"");

WriteLiteral(">");


#line 103 "SettingsRazorView.cshtml"
                                     Write(Model.Language["gui_theme_light"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                </select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group col-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-check\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"form-check-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"UseColorForAllNotesInDarkMode\"");

WriteLiteral(" v-model=\"UseColorForAllNotesInDarkMode\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"form-check-label\"");

WriteLiteral(" for=\"UseColorForAllNotesInDarkMode\"");

WriteLiteral(">");


#line 110 "SettingsRazorView.cshtml"
                                                                                       Write(Model.Language["gui_theme_color_all_dark"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                    </div>\r\n                </div>\r\n                <di" +
"v");

WriteLiteral(" class=\"form-group col-2\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"color\"");

WriteLiteral(" v-model=\"ColorForAllNotesInDarkModeHex\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"Color\"");

WriteLiteral(">");


#line 119 "SettingsRazorView.cshtml"
                                                     Write(Model.Language["gui_default_color"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" id=\"color-control\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"DefaultNoteColor\"");

WriteLiteral(" class=\"dropdown d-flex\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" id=\"Color\"");

WriteLiteral(" class=\"color-preview btn m-0 h-100 flex-fill\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" v-bind:style=\"{ backgroundColor: DefaultNoteColorHex }\"");

WriteLiteral(">\r\n                        </button>\r\n                        <div");

WriteLiteral(" class=\"dropdown-menu color-list\"");

WriteLiteral(" aria-labelledby=\"colorChooser\"");

WriteLiteral(">\r\n");


#line 125 "SettingsRazorView.cshtml"
                            

#line default
#line hidden

#line 125 "SettingsRazorView.cshtml"
                             foreach (var backgroundColor in @Model.NoteColorsHex)
                            {


#line default
#line hidden
WriteLiteral("                                <div");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "dropdown-item", true)
, Tuple.Create<string,object,bool> (" ", "color-btn", true)

#line 127 "SettingsRazorView.cshtml"
                            , Tuple.Create<string,object,bool> (" ", Model.GetDarkClass(backgroundColor)

#line default
#line hidden
, false)
);
WriteAttribute ("v-on:click", " v-on:click=\"", "\""
, Tuple.Create<string,object,bool> ("", "DefaultNoteColorHex=\'", true)

#line 127 "SettingsRazorView.cshtml"
                                                                                                    , Tuple.Create<string,object,bool> ("", backgroundColor

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteAttribute ("style", " style=\"", "\""
, Tuple.Create<string,object,bool> ("", "background-color:", true)

#line 127 "SettingsRazorView.cshtml"
                                                                                                                                               , Tuple.Create<string,object,bool> (" ", backgroundColor

#line default
#line hidden
, false)
);
WriteLiteral(">Lorem ipsum</div>\r\n");


#line 128 "SettingsRazorView.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n                </div" +
">\r\n            </div>\r\n        </form>\r\n\r\n        <h2>");


#line 135 "SettingsRazorView.cshtml"
       Write(Model.Language["gui"]);


#line default
#line hidden
WriteLiteral("</h2>\r\n        <form");

WriteLiteral(" class=\"mb-4 col-md-9 col-lg-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"FontSizeStep\"");

WriteLiteral(">");


#line 138 "SettingsRazorView.cshtml"
                                                            Write(Model.Language["gui_font_size"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"custom-range col-sm-6\"");

WriteLiteral(" type=\"range\"");

WriteLiteral(" id=\"FontSizeStep\"");

WriteLiteral(" v-model=\"FontSizeStep\"");

WriteLiteral(" min=\"-3\"");

WriteLiteral(" max=\"3\"");

WriteLiteral(" step=\"1\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"NoteMaxHeightStep\"");

WriteLiteral(">");


#line 144 "SettingsRazorView.cshtml"
                                                                 Write(Model.Language["gui_note_max_size"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"custom-range col-sm-6\"");

WriteLiteral(" type=\"range\"");

WriteLiteral(" id=\"NoteMaxHeightStep\"");

WriteLiteral(" v-model=\"NoteMaxHeightStep\"");

WriteLiteral(" min=\"-4\"");

WriteLiteral(" max=\"4\"");

WriteLiteral(" step=\"1\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"SelectedNoteInsertionMode\"");

WriteLiteral(">");


#line 151 "SettingsRazorView.cshtml"
                                                                         Write(Model.Language["gui_note_insertion"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"SelectedNoteInsertionMode\"");

WriteLiteral(" v-model=\"SelectedNoteInsertionMode\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"AtTop\"");

WriteLiteral(">");


#line 153 "SettingsRazorView.cshtml"
                                     Write(Model.Language["gui_note_insertion_top"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                    <option");

WriteLiteral(" value=\"AtBottom\"");

WriteLiteral(">");


#line 154 "SettingsRazorView.cshtml"
                                        Write(Model.Language["gui_note_insertion_bottom"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                </select>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"form-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-check\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"form-check-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"RememberLastTagFilter\"");

WriteLiteral(" v-model=\"RememberLastTagFilter\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"form-check-label\"");

WriteLiteral(" for=\"RememberLastTagFilter\"");

WriteLiteral(">");


#line 162 "SettingsRazorView.cshtml"
                                                                                   Write(Model.Language["gui_remember_last_tag_filter"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n\r\n            <div");

WriteLiteral(" class=\"form-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-check\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"form-check-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"HideClosedSafeNotes\"");

WriteLiteral(" v-model=\"HideClosedSafeNotes\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"form-check-label\"");

WriteLiteral(" for=\"HideClosedSafeNotes\"");

WriteLiteral(">");


#line 171 "SettingsRazorView.cshtml"
                                                                             Write(Model.Language["gui_hide_closed_safe_notes"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n\r\n");


#line 176 "SettingsRazorView.cshtml"
            

#line default
#line hidden

#line 176 "SettingsRazorView.cshtml"
             if (Model.CanKeepScreenOn)
            {


#line default
#line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"KeepScreenOpenStep\"");

WriteLiteral(">{{KeepScreenOnDurationTitle}}</label>\r\n                    <div");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"custom-range col-sm-6\"");

WriteLiteral(" type=\"range\"");

WriteLiteral(" id=\"KeepScreenOpenStep\"");

WriteLiteral(" v-model=\"KeepScreenOnDuration\"");

WriteLiteral(" min=\"1\"");

WriteLiteral(" max=\"30\"");

WriteLiteral(" step=\"1\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n");


#line 184 "SettingsRazorView.cshtml"
            }


#line default
#line hidden
WriteLiteral("        </form>\r\n\r\n        <h2>");


#line 187 "SettingsRazorView.cshtml"
       Write(Model.Language["sync"]);


#line default
#line hidden
WriteLiteral("</h2>\r\n        <form");

WriteLiteral(" class=\"mb-4 col-md-9 col-lg-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"SelectedAutoSyncMode\"");

WriteLiteral(">");


#line 190 "SettingsRazorView.cshtml"
                                                                    Write(Model.Language["sync_auto"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"SelectedAutoSyncMode\"");

WriteLiteral(" v-model=\"SelectedAutoSyncMode\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"Never\"");

WriteLiteral(">");


#line 192 "SettingsRazorView.cshtml"
                                     Write(Model.Language["sync_auto_never"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                    <option");

WriteLiteral(" value=\"CostFreeInternetOnly\"");

WriteLiteral(">");


#line 193 "SettingsRazorView.cshtml"
                                                    Write(Model.Language["sync_auto_costfree"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                    <option");

WriteLiteral(" value=\"Always\"");

WriteLiteral(">");


#line 194 "SettingsRazorView.cshtml"
                                      Write(Model.Language["sync_auto_always"]);


#line default
#line hidden
WriteLiteral("</option>\r\n                </select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"CloudStorageSettings\"");

WriteLiteral(">");


#line 198 "SettingsRazorView.cshtml"
                                                                    Write(Model.Language["cloud_service"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"CloudStorageSettings\"");

WriteLiteral(" v-model=\"AccountSummary\"");

WriteLiteral(" rows=\"4\"");

WriteLiteral(" readonly></textarea>\r\n            </div>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary mb-2 mr-1\"");

WriteLiteral(" v-on:click=\"ChangeCloudSettingsCommand\"");

WriteAttribute ("title", " title=\"", "\""

#line 201 "SettingsRazorView.cshtml"
                                                                              , Tuple.Create<string,object,bool> ("", Model.Language["cloud_change_settings_desc"]

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 201 "SettingsRazorView.cshtml"
                                                                                                                                                               Write(Model.Language["cloud_change_settings"]);


#line default
#line hidden
WriteLiteral("</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger mb-2 mr-1\"");

WriteLiteral(" v-on:click=\"ClearCloudSettingsCommand\"");

WriteLiteral(" v-bind:disabled=\"ClearCloudSettingsDisabled\"");

WriteAttribute ("title", " title=\"", "\""

#line 202 "SettingsRazorView.cshtml"
                                                                                                                       , Tuple.Create<string,object,bool> ("", Model.Language["cloud_clear_settings_desc"]

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 202 "SettingsRazorView.cshtml"
                                                                                                                                                                                                       Write(Model.Language["cloud_clear_settings"]);


#line default
#line hidden
WriteLiteral("</button>\r\n        </form>\r\n\r\n        <h2>");


#line 205 "SettingsRazorView.cshtml"
       Write(Model.Language["encryption"]);


#line default
#line hidden
WriteLiteral("</h2>\r\n        <form");

WriteLiteral(" class=\"mb-4 col-md-9 col-lg-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-row form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-form-label\"");

WriteLiteral(" for=\"SelectedEncryptionAlgorithm\"");

WriteLiteral(">");


#line 208 "SettingsRazorView.cshtml"
                                                                           Write(Model.Language["encryption_algorithm"]);


#line default
#line hidden
WriteLiteral("</label>\r\n                <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"SelectedEncryptionAlgorithm\"");

WriteLiteral(" v-model=\"SelectedEncryptionAlgorithm\"");

WriteLiteral(">\r\n");


#line 210 "SettingsRazorView.cshtml"
                    

#line default
#line hidden

#line 210 "SettingsRazorView.cshtml"
                     foreach (var algorithm in @Model.EncryptionAlgorithms)
                    {


#line default
#line hidden
WriteLiteral("                        <option");

WriteAttribute ("value", " value=\"", "\""

#line 212 "SettingsRazorView.cshtml"
, Tuple.Create<string,object,bool> ("", algorithm.Value

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 212 "SettingsRazorView.cshtml"
                                                    Write(algorithm.Description);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 213 "SettingsRazorView.cshtml"
                    }


#line default
#line hidden
WriteLiteral("                </select>\r\n            </div>\r\n        </form>\r\n    </div>\r\n\r\n   " +
" <div hidden>\r\n");


#line 220 "SettingsRazorView.cshtml"
        

#line default
#line hidden

#line 220 "SettingsRazorView.cshtml"
          WriteLiteral(Model.Icon.LoadIcon("settings", new[] { new KeyValuePair<string, string>("id", "svg-settings") }));

#line default
#line hidden
WriteLiteral("\r\n    </div>\r\n</div></body>\r\n</html>\r\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class SettingsRazorViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
